development:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/muserblog/muserblog_development.sqlite

test:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/muserblog/tmp/muserblog_test.sqlite

production:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/muserblog/muserblog_production.sqlite
